language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install numpy ipython scipy h5py matplotlib betagen pytest pytest-cov cython
  - python setup.py install
script:
  - python -m pytest -vv --cov=popsynth/
#  - codecov --token=a9aece23-c28a-4769-ad05-eb33579b6c55
